pre-release-commit-message = "release: {{crate_name}} v{{version}}"
tag-message                = "release: {{crate_name}} v{{version}}"
sign-commit                = true
sign-tag                   = true
